/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui.tugas.pertemuan2;

/**
 *
 * @author Lenovo
 */
public class calculatorBagunDatar extends javax.swing.JFrame {

    /**
     * Creates new form calculatorBagunDatar
     */
    double nilai1, nilai2, hasil, lingkaran, alas, tinggi, sisi, keliling, luas;

    public calculatorBagunDatar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHasilLuasPersegipanjang = new javax.swing.JTextField();
        txtInputPanjangPersegiPanjang1 = new javax.swing.JTextField();
        txtInputLebarPersegiPanjang2 = new javax.swing.JTextField();
        btnHitungPersegiPanjang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnHitungLingkaran = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtHasilLuasLingkaran = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPhi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTinggi = new javax.swing.JTextField();
        btnLuasSegitiga = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtHasilSegitiga = new javax.swing.JTextField();
        txtJariJari = new javax.swing.JTextField();
        txtAlas = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtInputSisi = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnHitungPersegi = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtHasilLuasPersegi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtHasilKelilingPersegipanjang1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtHasilKelilingLingkaran = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtHasilKelilingPersegi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 255));
        jLabel1.setText("Calculator Bangun Datar");

        jLabel2.setText("P");

        jLabel3.setText("L");

        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("Persegi panjang");

        jLabel5.setText("Hitung Luas dan Keliling");

        jLabel6.setText("Hasil Luas");

        txtHasilLuasPersegipanjang.setForeground(new java.awt.Color(0, 0, 0));

        btnHitungPersegiPanjang.setBackground(new java.awt.Color(0, 204, 204));
        btnHitungPersegiPanjang.setForeground(new java.awt.Color(0, 0, 0));
        btnHitungPersegiPanjang.setText("Hitung persegi panjang");
        btnHitungPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungPersegiPanjangActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("Lingkaran");

        jLabel8.setText("Jari-jari");

        jLabel9.setText("Hitung Luas dan Keliling");

        btnHitungLingkaran.setBackground(new java.awt.Color(0, 204, 204));
        btnHitungLingkaran.setForeground(new java.awt.Color(0, 0, 0));
        btnHitungLingkaran.setText("Hitung Lingkaran");
        btnHitungLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungLingkaranActionPerformed(evt);
            }
        });

        jLabel10.setText("Hasil Luas");

        txtHasilLuasLingkaran.setForeground(new java.awt.Color(0, 0, 0));
        txtHasilLuasLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHasilLuasLingkaranActionPerformed(evt);
            }
        });

        jLabel11.setText("Chose phi");

        jLabel12.setForeground(new java.awt.Color(255, 102, 51));
        jLabel12.setText("Segitiga");

        jLabel13.setText("Alas");

        jLabel14.setText("Tinggi");
        jLabel14.setToolTipText("");

        btnLuasSegitiga.setBackground(new java.awt.Color(0, 204, 204));
        btnLuasSegitiga.setForeground(new java.awt.Color(0, 0, 0));
        btnLuasSegitiga.setText("Luas");
        btnLuasSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuasSegitigaActionPerformed(evt);
            }
        });

        jLabel16.setText("Hasil");

        txtHasilSegitiga.setForeground(new java.awt.Color(0, 0, 0));

        jLabel17.setForeground(new java.awt.Color(255, 102, 51));
        jLabel17.setText("Persegi");

        jLabel18.setText("Sisi");

        jLabel20.setText("Hitung Luas dan Keliling");

        btnHitungPersegi.setBackground(new java.awt.Color(0, 204, 204));
        btnHitungPersegi.setForeground(new java.awt.Color(0, 0, 0));
        btnHitungPersegi.setText("Hitung persegi");
        btnHitungPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungPersegiActionPerformed(evt);
            }
        });

        jLabel21.setText("Hasil Luas");

        txtHasilLuasPersegi.setForeground(new java.awt.Color(0, 0, 0));

        jLabel15.setText("Hasil Keliling");

        txtHasilKelilingPersegipanjang1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel19.setText("Hasil Keliling");

        txtHasilKelilingLingkaran.setForeground(new java.awt.Color(0, 0, 0));
        txtHasilKelilingLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHasilKelilingLingkaranActionPerformed(evt);
            }
        });

        jLabel22.setText("Hasil Keliling");

        txtHasilKelilingPersegi.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHasilLuasPersegipanjang, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(txtHasilKelilingPersegipanjang1)))
                            .addComponent(btnHitungPersegiPanjang)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInputPanjangPersegiPanjang1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtInputLebarPersegiPanjang2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(jLabel17))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtHasilKelilingPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtHasilLuasPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtInputSisi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel20)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnHitungPersegi))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(btnHitungLingkaran)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtJariJari, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHasilLuasLingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(txtHasilKelilingLingkaran)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtHasilSegitiga))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTinggi)
                                            .addComponent(txtAlas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnLuasSegitiga)))
                        .addGap(46, 46, 46))))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtInputPanjangPersegiPanjang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHitungPersegiPanjang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHasilLuasPersegipanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHasilKelilingPersegipanjang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtInputLebarPersegiPanjang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJariJari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHitungLingkaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtHasilLuasLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(txtHasilKelilingLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtInputSisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHitungPersegi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtHasilLuasPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtAlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLuasSegitiga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtHasilSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtHasilKelilingPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungPersegiPanjangActionPerformed
        // TODO add your handling code here:
        nilai1 = Double.parseDouble(txtInputPanjangPersegiPanjang1.getText());
        nilai2 = Double.parseDouble(txtInputLebarPersegiPanjang2.getText());
//        Luas
        luas = nilai1 * nilai2;
        txtHasilLuasPersegipanjang.setText(String.valueOf(luas));
//        keliling
        keliling = 2 * (nilai1 + nilai2);
        txtHasilKelilingPersegipanjang1.setText(String.valueOf(keliling));
    }//GEN-LAST:event_btnHitungPersegiPanjangActionPerformed

    private void btnHitungLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungLingkaranActionPerformed
        // TODO add your handling code here:
        lingkaran = Double.parseDouble(txtJariJari.getText());
        Double phi = Double.parseDouble(txtPhi.getText());
        // Periksa apakah phi adalah 3.14 atau 22/7 (dengan pendekatan toleransi)
        if (Math.abs(phi - 3.14) < 0.0001) { // Perbandingan double dengan toleransi digunakan untuk menghindari kesalahan perbandingan antara bilangan desimal dengan tipe double.
//            math pow untuk menghitung pangkat
            luas = 3.14 * Math.pow(lingkaran, 2); // Menghitung luas lingkaran dengan phi 3.14
            txtHasilLuasLingkaran.setText(String.valueOf(luas)); // Menampilkan hasil ke text field
            keliling = 2 * 3.14 * lingkaran; // Menghitung keliling lingkaran dengan phi 3.14
            txtHasilKelilingLingkaran.setText(String.valueOf(keliling)); // Menampilkan hasil ke text field
        } else if (Math.abs(phi - 22.0 / 7) < 0.0001) { // digunakan untuk menghindari kesalahan perbandingan antara bilangan desimal dengan tipe double.
//            math pow untuk menghitung pangkat
            luas = 3.14 * Math.pow(lingkaran, 2); // Menghitung luas lingkaran dengan phi 22/7
            txtHasilLuasLingkaran.setText(String.valueOf(luas));
            keliling = 2 * 3.14 * lingkaran; // Menghitung keliling lingkaran dengan phi 3.14
            txtHasilKelilingLingkaran.setText(String.valueOf(keliling)); // Menampilkan hasil ke text field
        } else {
            System.out.println("Phi tidak ditemukan"); // Jika phi tidak valid
        }
    }//GEN-LAST:event_btnHitungLingkaranActionPerformed

    private void btnLuasSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuasSegitigaActionPerformed
        // TODO add your handling code here:
        alas = Double.parseDouble(txtAlas.getText());
        tinggi = Double.parseDouble(txtTinggi.getText());
        hasil = 0.5 * alas * tinggi;
        txtHasilSegitiga.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnLuasSegitigaActionPerformed

    private void btnHitungPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungPersegiActionPerformed
        // TODO add your handling code here:
//        luas
        sisi = Double.parseDouble(txtInputSisi.getText());
        luas = sisi * sisi;
        txtHasilLuasPersegi.setText(String.valueOf(luas));
//        keliling
        sisi = Double.parseDouble(txtInputSisi.getText());
        keliling = sisi * sisi * sisi * sisi;
        txtHasilKelilingPersegi.setText(String.valueOf(keliling));
    }//GEN-LAST:event_btnHitungPersegiActionPerformed

    private void txtHasilLuasLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHasilLuasLingkaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHasilLuasLingkaranActionPerformed

    private void txtHasilKelilingLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHasilKelilingLingkaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHasilKelilingLingkaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatorBagunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatorBagunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatorBagunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatorBagunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatorBagunDatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitungLingkaran;
    private javax.swing.JButton btnHitungPersegi;
    private javax.swing.JButton btnHitungPersegiPanjang;
    private javax.swing.JButton btnLuasSegitiga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAlas;
    private javax.swing.JTextField txtHasilKelilingLingkaran;
    private javax.swing.JTextField txtHasilKelilingPersegi;
    private javax.swing.JTextField txtHasilKelilingPersegipanjang1;
    private javax.swing.JTextField txtHasilLuasLingkaran;
    private javax.swing.JTextField txtHasilLuasPersegi;
    private javax.swing.JTextField txtHasilLuasPersegipanjang;
    private javax.swing.JTextField txtHasilSegitiga;
    private javax.swing.JTextField txtInputLebarPersegiPanjang2;
    private javax.swing.JTextField txtInputPanjangPersegiPanjang1;
    private javax.swing.JTextField txtInputSisi;
    private javax.swing.JTextField txtJariJari;
    private javax.swing.JTextField txtPhi;
    private javax.swing.JTextField txtTinggi;
    // End of variables declaration//GEN-END:variables
}
