/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui.tugas.pertemuan2;

/**
 *
 * @author Lenovo
 */
public class calculatorBagunDatar extends javax.swing.JFrame {

    /**
     * Creates new form calculatorBagunDatar
     */
    double nilai1, nilai2, hasil, lingkaran, alas, tinggi, sisi;

    public calculatorBagunDatar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHasilPersegipanjang = new javax.swing.JTextField();
        txtInputPanjangPersegiPanjang1 = new javax.swing.JTextField();
        txtInputLebarPersegiPanjang2 = new javax.swing.JTextField();
        btnLuasPersegiPanjang = new javax.swing.JButton();
        btnKelilingPersegiPanjang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnLuasLingkaran = new javax.swing.JButton();
        btnKelilingLingkaran = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtHasilLingkaran = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPhi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTinggi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnLuasSegitiga = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtHasilSegitiga = new javax.swing.JTextField();
        txtJariJari = new javax.swing.JTextField();
        txtAlas = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtInputSisi = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnLuasPersegi = new javax.swing.JButton();
        btnKelilingPersegi = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtHasilPersegi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setText("Calculator Bangun Datar");

        jLabel2.setText("Panjang");

        jLabel3.setText("Lebar");

        jLabel4.setText("Persegi panjang");

        jLabel5.setText("Pilih Luas atau Keliling");

        jLabel6.setText("Hasil");

        btnLuasPersegiPanjang.setText("Luas");
        btnLuasPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuasPersegiPanjangActionPerformed(evt);
            }
        });

        btnKelilingPersegiPanjang.setText("Keliling");
        btnKelilingPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelilingPersegiPanjangActionPerformed(evt);
            }
        });

        jLabel7.setText("Lingkaran");

        jLabel8.setText("Jari-jari");

        jLabel9.setText("Pilih Luas atau Keliling");

        btnLuasLingkaran.setText("Luas");
        btnLuasLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuasLingkaranActionPerformed(evt);
            }
        });

        btnKelilingLingkaran.setText("Keliling");
        btnKelilingLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelilingLingkaranActionPerformed(evt);
            }
        });

        jLabel10.setText("Hasil");

        jLabel11.setText("Chose phi");

        jLabel12.setText("Segitiga");

        jLabel13.setText("Alas");

        jLabel14.setText("Tinggi");
        jLabel14.setToolTipText("");

        jLabel15.setText("Pilih Luas atau Keliling");

        btnLuasSegitiga.setText("Luas");
        btnLuasSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuasSegitigaActionPerformed(evt);
            }
        });

        jLabel16.setText("Hasil");

        jLabel17.setText("Persegi");

        jLabel18.setText("Sisi");

        jLabel20.setText("Pilih Luas atau Keliling");

        btnLuasPersegi.setText("Luas");
        btnLuasPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuasPersegiActionPerformed(evt);
            }
        });

        btnKelilingPersegi.setText("Keliling");
        btnKelilingPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelilingPersegiActionPerformed(evt);
            }
        });

        jLabel21.setText("Hasil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(284, 284, 284))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtInputLebarPersegiPanjang2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtInputPanjangPersegiPanjang1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHasilPersegipanjang, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLuasPersegiPanjang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKelilingPersegiPanjang)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPhi)
                            .addComponent(txtJariJari, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLuasLingkaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKelilingLingkaran))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHasilLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHasilSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTinggi)
                                    .addComponent(txtAlas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnLuasSegitiga)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(txtInputSisi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17)
                            .addComponent(jLabel20)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLuasPersegi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKelilingPersegi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHasilPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtInputPanjangPersegiPanjang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtInputLebarPersegiPanjang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuasPersegiPanjang)
                            .addComponent(btnKelilingPersegiPanjang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtHasilPersegipanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtJariJari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuasLingkaran)
                            .addComponent(btnKelilingLingkaran))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtHasilLingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtAlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(btnLuasSegitiga))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtInputSisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLuasPersegi)
                                    .addComponent(btnKelilingPersegi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(txtHasilPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtHasilSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuasPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuasPersegiPanjangActionPerformed
        // TODO add your handling code here:
        nilai1 = Double.parseDouble(txtInputPanjangPersegiPanjang1.getText());
        nilai2 = Double.parseDouble(txtInputLebarPersegiPanjang2.getText());
        hasil = nilai1 * nilai2;
        txtHasilPersegipanjang.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnLuasPersegiPanjangActionPerformed

    private void btnKelilingPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelilingPersegiPanjangActionPerformed
        // TODO add your handling code here:
        nilai1 = Double.parseDouble(txtInputPanjangPersegiPanjang1.getText());
        nilai2 = Double.parseDouble(txtInputLebarPersegiPanjang2.getText());
        hasil = 2 * (nilai1 + nilai2);
        txtHasilPersegipanjang.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnKelilingPersegiPanjangActionPerformed

    private void btnLuasLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuasLingkaranActionPerformed
        // TODO add your handling code here:
        lingkaran = Double.parseDouble(txtJariJari.getText());
        Double phi = Double.parseDouble(txtPhi.getText());
        // Periksa apakah phi adalah 3.14 atau 22/7 (dengan pendekatan toleransi)
        if (Math.abs(phi - 3.14) < 0.0001) { // Perbandingan double dengan toleransi
            hasil = 3.14 * Math.pow(lingkaran, 2); // Menghitung luas lingkaran dengan phi 3.14
            txtHasilLingkaran.setText(String.valueOf(hasil)); // Menampilkan hasil ke text field
        } else if (Math.abs(phi - 22/7) < 0.0001) {
            hasil = 3.14 * Math.pow(lingkaran, 2); // Menghitung luas lingkaran dengan phi 22/7
            txtHasilLingkaran.setText(String.valueOf(hasil));
        } else {
            System.out.println("Phi tidak ditemukan"); // Jika phi tidak valid
        }
    }//GEN-LAST:event_btnLuasLingkaranActionPerformed

    private void btnKelilingLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelilingLingkaranActionPerformed
        // TODO add your handling code here:
        lingkaran = Double.parseDouble(txtJariJari.getText());
        Double phi = Double.parseDouble(txtPhi.getText());
        // Periksa apakah phi adalah 3.14 atau 22/7 (dengan pendekatan toleransi)
        if (Math.abs(phi - 3.14) < 0.0001) { // Perbandingan double dengan toleransi
            hasil = 2 * 3.14 * lingkaran; // Menghitung keliling lingkaran dengan phi 3.14
            txtHasilLingkaran.setText(String.valueOf(hasil)); // Menampilkan hasil ke text field
        } else if (Math.abs(phi - 22/7) < 0.0001) {
            hasil = 2 * 3.14 * lingkaran; // Menghitung keliling lingkaran dengan phi 22/7
            txtHasilLingkaran.setText(String.valueOf(hasil));
        } else {
            System.out.println("Phi tidak ditemukan"); // Jika phi tidak valid
        }
    }//GEN-LAST:event_btnKelilingLingkaranActionPerformed

    private void btnLuasSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuasSegitigaActionPerformed
        // TODO add your handling code here:
        alas = Double.parseDouble(txtAlas.getText());
        tinggi = Double.parseDouble(txtTinggi.getText());
        hasil = 0.5 * alas * tinggi;
        txtHasilSegitiga.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnLuasSegitigaActionPerformed

    private void btnLuasPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuasPersegiActionPerformed
        // TODO add your handling code here:
        sisi = Double.parseDouble(txtInputSisi.getText());
        hasil = sisi * sisi;
        txtHasilPersegi.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnLuasPersegiActionPerformed

    private void btnKelilingPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelilingPersegiActionPerformed
        // TODO add your handling code here:
        sisi = Double.parseDouble(txtInputSisi.getText());
        hasil = sisi * sisi * sisi * sisi;
        txtHasilPersegi.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnKelilingPersegiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatorBagunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatorBagunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatorBagunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatorBagunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatorBagunDatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKelilingLingkaran;
    private javax.swing.JButton btnKelilingPersegi;
    private javax.swing.JButton btnKelilingPersegiPanjang;
    private javax.swing.JButton btnLuasLingkaran;
    private javax.swing.JButton btnLuasPersegi;
    private javax.swing.JButton btnLuasPersegiPanjang;
    private javax.swing.JButton btnLuasSegitiga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAlas;
    private javax.swing.JTextField txtHasilLingkaran;
    private javax.swing.JTextField txtHasilPersegi;
    private javax.swing.JTextField txtHasilPersegipanjang;
    private javax.swing.JTextField txtHasilSegitiga;
    private javax.swing.JTextField txtInputLebarPersegiPanjang2;
    private javax.swing.JTextField txtInputPanjangPersegiPanjang1;
    private javax.swing.JTextField txtInputSisi;
    private javax.swing.JTextField txtJariJari;
    private javax.swing.JTextField txtPhi;
    private javax.swing.JTextField txtTinggi;
    // End of variables declaration//GEN-END:variables
}
